### ISSUE TITLE
疑问：加载网络图片使用回调自行调用SDImage

### ISSUE THREAD

**Issue by lennondong** [JxbSir/JXBAdPageView#6]
这句意思是，代码会自动判断图片的加载方式，还是说，开发者自己去调用SDImage方法？在哪里使用SDImage方法？

**Comment by JxbSir** [comment]
此控件没有依赖于SD，所以需要开发者实现Delegatge自行调用SD现实：
@protocol JXBAdPageViewDelegate <NSObject>
/**
-  加载网络图片使用回调自行调用SDImage
  *
-  @param imgView
-  @param imgUrl
  */
  - (void)setWebImage:(UIImageView_)imgView imgUrl:(NSString_)imgUrl;
    @end
